### ISSUE TITLE
Offene Punkte in Testinstallation

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/kitodo-presentation-docker#12]
Offen in Stand 2022-07-12:

- [x] Nach der Anmeldung an das TYPO3 Backend erscheint die Fehlermeldung: `Missing referrer for /main`. 
Das ist noch zu reparieren. 
Ich bin nach dieser Anleitung vorgegangen: https://www.wacon.de/typo3-know-how/missing-referrer-for-main.html.
- [x] Ein paar Apache2-Module müssen noch aktiviert werden, siehe
https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/SystemRequirements/Index.html#web-server.
Es fehlten `expires`, `headers` und `rewrite`.
- [x] Dieser symbolische Link fehlte noch:
`root@cc8a04ee44cc:/var/www/html# ls -l .htaccess`
`lrwxrwxrwx 1 root root 25 Jul 13 13:02 .htaccess -> ../typo3/public/.htaccess`
- [ ] Der originale DFG-Viewer hat noch Links zu Datenschutzerklärung und Impressum. Die brauchen wir auch, aber verlinkt zu unseren jeweiligen Seiten.
- [ ] Volltextanzeige funktioniert nicht bei Umstellung auf englischsprachige Bedienoberfläche.

Stand 2022-07-14:

- [x] Im Docker-Image fehlen die englischen Übersetzungen (momentan korrigiert in TYPO3).
- [x] Das Docker-Image verwendet keine "sprechenden" URLs (momentan korrigiert in TYPO3).

Optional 2022-07-14:

- [x] Zeilengetreue Ansicht

**Comment by csidirop** [comment]
Punkt 1 sollte mi PR #13 gelöst sein.

**Comment by csidirop** [comment]
Punkt 2 sollte mit folgenden commit gelöst sein: [Activate apache2 mods](https://github.com/csidirop/typo3-docker/commit/6e011fb93190edf8df379784a66a26e090723962)

**Comment by stweil** [comment]
Stand 2022-07-14:

- Im Docker-Image fehlen die englischen Übersetzungen (momentan korrigiert in TYPO3).
- Das Docker-Image verwendet keine "sprechenden" URLs (momentan korrigiert in TYPO3).

**Comment by stweil** [comment]
Offene Frage: Sollten wir den Volltext zeilengetreu (wie auf digi) oder so wie im Original-DFG-Viewer anzeigen?

**Comment by csidirop** [comment]
> Offene Frage: Sollten wir den Volltext zeilengetreu (wie auf digi) oder so wie im Original-DFG-Viewer anzeigen?

Ich finde das zeilengetreu intuitiver ist und optisch besser aussieht. Denke das kann man später angehen.

**Comment by csidirop** [comment]
Geschlossen weil wir nun ein [Projekt ](https://github.com/orgs/UB-Mannheim/projects/2) angelegt haben
