### ISSUE TITLE
[presentation] English fulltextview doesn't work properly

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/kitodo-presentation-docker#19]
Volltextanzeige funktioniert nicht bei Umstellung auf englischsprachige Bedienoberfläche.

[#12](https://github.com/UB-Mannheim/kitodo-presentation-docker/issues/12)

**Comment by csidirop** [comment]
Resolved with https://github.com/csidirop/kitodo-presentation/commit/4954c813f358a9eef25e9d26025ad3e373db2d11
