### ISSUE TITLE
[docker] Add fulltext search for generated fulltexts

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/kitodo-presentation-docker#26]
We already generate ALTO files for any METS file. Storing that METS file together with those ALTO files is sufficient for using the standard process how Kitodo.Presentation builds a search index.

Such a search index can be configured to contain any metadata from the METS files (e.g. authors, titles, years of publication) and the fulltext.

As soon as there exists a search index, it is a small step to make that available in the web frontend. There could be a search field which allows entering a search expression and starting a search, and there could be a display for the results of that search. There could also be an overview of all processed items, so users can browse those items which were enriched with fulltext.

**Comment by csidirop** [comment]
For the record:
I have a docker configuration with configured solr for presentation. There are only the TYPO3 page and content settings missing.

https://github.com/csidirop/kitodo-presentation-docker/tree/feature/solr

I will finish that when I found some spare time.

**Comment by csidirop** [comment]
Is now merged into https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-5.3-ocr 
Even though full text search does not yet work correctly. Metadata search works when documents get indexed.

**Comment by csidirop** [comment]
Solr with metadata and fulltext search is working now: https://github.com/csidirop/kitodo-presentation-docker/tree/update-solr

The layout is just trash.
