### ISSUE TITLE
[presentation & DFG-Viewer] Use latest code with TYPO3 release 10

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/kitodo-presentation-docker#29]
The [dfg-viewer-5.3-ocr branch](https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-5.3-ocr) is currently based on older code which requires the old TYPO3 release 9.

How much work is needed to update that to newer code? Is there anything still missing to get support for newer TYPO3 releases?

**Comment by csidirop** [comment]
This is a good question, but one that should be asked here https://github.com/slub/dfg-viewer/issues

**Comment by stweil** [comment]
That pull request was merged, the issue is closed. The dfg-viewer master branch should support TYPO3 10.4 (see [here](https://github.com/slub/dfg-viewer/blob/master/composer.json#L40)).

**Comment by csidirop** [comment]
Yes but its still not a final version and can therefore undergo yet greater structural changes. Sure we could test it.

**Comment by csidirop** [comment]
Docker Image with the newest DFG-Viewer Code: [dfg-viewer-dev](https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-dev)
OCR-On-Demand need more time.

**Comment by csidirop** [comment]
Devbranch: https://github.com/csidirop/kitodo-presentation-docker/tree/update

At this point there is only on issue left with the button (de-)activating den full text. It is deactivated when no full texts are remote available. So old or newly generated full text wont get shown.

Todo:
[ ] Fix the full text button
[ ] Wait till https://github.com/slub/dfg-viewer/pull/221 got merged
[ ] Wait till https://github.com/kitodo/kitodo-presentation/issues/908 is resolved
